version: 2

jobs:
  build:
    working_directory: ~/tf-aws-state-bucket
    environment:
      BASH_ENV: local.env
    docker:
    - image: quay.io/feedyard/circleci-infra-agent
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: confirm Docker
        command: docker info
    - run:
        name: terraform files syntax and style check
        command: invoke stylecheck
    # when kitchen-terraform / awspec compatibility issues are resolved, re-introduce the test fixture and
    # publish to terraform module registry